# Generated by Django 3.1.2 on 2020-10-09 18:41

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201009_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phone_field.models.PhoneField(default=9039139844, max_length=31, unique=True),
            preserve_default=False,
        ),
    ]
