# Generated by Django 3.1.2 on 2020-10-09 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='In_List',
        ),
        migrations.AddField(
            model_name='contact',
            name='In_List',
            field=models.ManyToManyField(blank=True, related_name='from_person_contact_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
